### ISSUE TITLE
User changing names crashes IRC to Game chat forwarding

### ISSUE THREAD

**Issue by jmurrayufo** [blay09/EiraIRC#185]
Playing on a FTB Direwolf20 v1.1.1 server. 

Installed version: eirairc-mc1.7.10-2.8.128.jar

Note that the bot continues to be able to forward mine-craft messages to the IRC channel at all times, and never stops being able to do this. 

User in the IRC side of the change changed their name, and caused the following error to show up in the logs. 

[17:58:59] [Thread-12/ERROR] [FML/eirairc]: Exception caught during firing event net.blay09.mods.eirairc.api.event.IRCUserNickChangeEvent@4cb4680e:
java.lang.NullPointerException
        at net.blay09.mods.eirairc.util.MessageFormat.formatChatComponent(MessageFormat.java:310) ~[MessageFormat.class:?]
        at net.blay09.mods.eirairc.handler.IRCEventHandler.onNickChange(IRCEventHandler.java:33) ~[IRCEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_550_IRCEventHandler_onNickChange_IRCUserNickChangeEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at net.blay09.mods.eirairc.irc.IRCConnectionImpl.handleMessage(IRCConnectionImpl.java:414) [IRCConnectionImpl.class:?]
        at net.blay09.mods.eirairc.irc.IRCConnectionImpl.run(IRCConnectionImpl.java:189) [IRCConnectionImpl.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[17:58:59] [Thread-12/ERROR] [FML/eirairc]: Index: 1 Listeners:
[17:58:59] [Thread-12/ERROR] [FML/eirairc]: 0: LOWEST
[17:58:59] [Thread-12/ERROR] [FML/eirairc]: 1: ASM: net.blay09.mods.eirairc.handler.IRCEventHandler@2b71797d onNickChange(Lnet/blay09/mods/eirairc/api/event/IRCUserNickChangeEvent;)V

The error is reproducible, and is corrected by disconnecting from the IRC server and reconnecting (a channel leave/join will not work). 

Further logs, configs or boot up examples available upon request.

**Comment by blay09** [comment]
This was fixed in #176, update to the latest Jenkins build to solve.

http://jenkins.blay09.net/

**Comment by jmurrayufo** [comment]
Can confirm this fixes our issue.
