### ISSUE TITLE
EiraIRC Dropping Connection

### ISSUE THREAD

**Issue by pacificfils** [blay09/EiraIRC#327]
I am unable to connect to a Slack server via EiraIRC:

```
[01:24:12] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:226]: :slackbot PRIVMSG kazwolfe :VERSION
[01:24:12] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:226]: :irc.tinyspeck.com 004 irc.tinyspeck.com IRC-SLACK gateway
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:226]: :irc.tinyspeck.com 001 kazwolfe Welcome to Slack IRC Gateway server kazwolfe!~kazwolfe@10.0.23.98
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:226]: :irc.tinyspeck.com 005 kazwolfe MAP SILENCE=15 WHOX WALLCHOPS WALLVOICES USERIP CPRIVMSG CNOTICE MODES=6 MAXCHANNELS=100 SAFELIST :are supported by this server
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:226]: :irc.tinyspeck.com 005 kazwolfe NICKLEN=32 TOPICLEN=160 AWAYLEN=160 CHANTYPES=# PREFIX=(ov)@+ CHANMODES=b,k,l,rimnpst CASEMAPPING=rfc1459 :are supported by this server
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:226]: :irc.tinyspeck.com 251 kazwolfe :there are 12 users 
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:handleNumericMessage:422]: Ignoring message code: 251 (2 arguments)
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:226]: :irc.tinyspeck.com 375 kazwolfe :Message of the day
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:handleNumericMessage:422]: Ignoring message code: 375 (2 arguments)
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:226]: :irc.tinyspeck.com 372 kazwolfe :WELCOME TO SLACK...
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:handleNumericMessage:422]: Ignoring message code: 372 (2 arguments)
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:226]: :irc.tinyspeck.com 376 kazwolfe :End of MOTD command
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:handleNumericMessage:428]: Unhandled message code: 376 (2 arguments)
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:226]: :kazwolfe!kazwolfe@irc.tinyspeck.com JOIN #server-alerts
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:226]: :irc.tinyspeck.com 332 kazwolfe #server-alerts :
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eirairc.util.IRCFormatting.toMC(IRCFormatting.java:114)
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eirairc.util.MessageFormat.formatChatComponent(MessageFormat.java:335)
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eirairc.handler.IRCEventHandler.fireChannelTopicEvent(IRCEventHandler.java:309)
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eirairc.irc.IRCConnectionImpl.handleNumericMessage(IRCConnectionImpl.java:386)
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eirairc.irc.IRCConnectionImpl.run(IRCConnectionImpl.java:230)
[01:24:18] [IRC (REDACTED.irc.slack.com)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
[01:24:18] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.net.SocketException: Socket is closed
[01:24:18] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1500)
[01:24:18] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1521)
[01:24:18] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
[01:24:18] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
[01:24:18] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
[01:24:18] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
[01:24:18] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
[01:24:18] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
[01:24:18] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.BufferedWriter.flush(BufferedWriter.java:254)
[01:24:18] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eirairc.irc.IRCSender.run(IRCSender.java:62)
[01:24:18] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
```
The connection works fine using other IRC clients, so it has to be something with EiraIRC.

**Comment by blay09** [comment]
Fixed version available on http://jenkins.blay09.net/

**Comment by pacificfils** [comment]
You're awesome, Blay.
