### ISSUE TITLE
Server Passwords aren't being saved

### ISSUE THREAD

**Issue by pacificfils** [blay09/EiraIRC#330]
On Build 258.

**Steps to Reproduce**:

1. Add a server with a password
2. Close Minecraft
3. Re-Open Minecraft

**Log File:**

```
[01:57:19] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:226]: :slackbot PRIVMSG kazwolfe :VERSION
[01:57:19] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:226]: :irc.tinyspeck.com 004 irc.tinyspeck.com IRC-SLACK gateway
[01:57:24] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:226]: :slackbot PRIVMSG kazwolfe : no password 
[01:57:24] [IRC (REDACTED.irc.slack.com)/INFO] [STDOUT/]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:226]: 444 kazwolfe :no password!!!
[01:57:24] [IRC (REDACTED.irc.slack.com)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ArrayIndexOutOfBoundsException: 2
[01:57:24] [IRC (REDACTED.irc.slack.com)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eirairc.handler.IRCEventHandler.fireIRCErrorEvent(IRCEventHandler.java:488)
[01:57:24] [IRC (REDACTED.irc.slack.com)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eirairc.irc.IRCConnectionImpl.handleNumericMessage(IRCConnectionImpl.java:425)
[01:57:24] [IRC (REDACTED.irc.slack.com)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eirairc.irc.IRCConnectionImpl.run(IRCConnectionImpl.java:230)
[01:57:24] [IRC (REDACTED.irc.slack.com)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
[01:57:24] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.net.SocketException: Socket is closed
[01:57:24] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1500)
[01:57:24] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1521)
[01:57:24] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
[01:57:24] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
[01:57:24] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
[01:57:24] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
[01:57:24] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
[01:57:24] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
[01:57:24] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.BufferedWriter.flush(BufferedWriter.java:254)
[01:57:24] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eirairc.irc.IRCSender.run(IRCSender.java:62)
[01:57:24] [IRCSender/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
```

An `eirairc.auth` file exists in the Minecraft root, with the following contents:

```
{
  "servers": {
    "REDACTED.irc.slack.com": "<correct password>"
  },
  "channels": {},
  "nickserv": {}
}
```

Additionally, the server configs in the `config/eirairc/servers.json` does not hold the password, even after being manually set.

**Comment by pacificfils** [comment]
I'm sorry for all the bug reports. :(

**Comment by blay09** [comment]
The servers.json is no longer supposed to hold the password, that's what the .auth file is for now (to separate private from not-so-private more clearly).

This is fixed in the latest build (I simply forgot to call the load() function on 1.8...).

Don't worry about bug reports, they are great and I hate it when people just silently accept the mod misbehaving. :)
