### ISSUE TITLE
Constantly connecting and disconnecting

### ISSUE THREAD

**Issue by Antillar** [blay09/EiraIRC#356]
Each time the client connects, the log file has these lines added. Client immediately disconnects.

[17:28:55] [IRC (irc.esper.net)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ArrayIndexOutOfBoundsException: -1
[17:28:55] [IRC (irc.esper.net)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eirairc.util.ChatComponentBuilder.lang(ChatComponentBuilder.java:34)
[17:28:55] [IRC (irc.esper.net)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eirairc.util.Utils.sendUserList(Utils.java:101)
[17:28:55] [IRC (irc.esper.net)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eirairc.handler.IRCEventHandler.fireChannelJoinedEvent(IRCEventHandler.java:660)
[17:28:55] [IRC (irc.esper.net)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eirairc.irc.IRCConnectionImpl.handleNumericMessage(IRCConnectionImpl.java:393)
[17:28:55] [IRC (irc.esper.net)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eirairc.irc.IRCConnectionImpl.run(IRCConnectionImpl.java:235)
[17:28:55] [IRC (irc.esper.net)/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by MightyStick** [comment]
Hello
